### ISSUE TITLE
[enhancement]: Tmodloader

### ISSUE THREAD

**Issue by Chocolate-Jeff** [pelican-eggs/games-standalone#10]
[Not a bug, but no way to put enhancement]
### Panel Version

v1.11.7

### Wings Version

v1.11.11

### Service

terraria/tmodloader

### Modified

No, I did not modify the egg

### Expected Behavior

In the tmodloader install script, the "latest" version tag should pull from the latest stable github release automatically:https://github.com/tModLoader/tModLoader/releases/latest

### Actual Behavior

Instead, the tmodloader latest version tag pulls from the top release of https://github.com/tModLoader/tModLoader/releases/, which is the latest Pre-release most of the time, and there really isn't a good way to fix this other then manually setting the tag every time tmodloader updates when the entire point of the latest tag should be to not have to change the environment variable anytime. There should at least be a tag that pulls from https://github.com/tModLoader/tModLoader/releases/latest

### Steps To Reproduce

N/A

### Install logs

N/A

**Comment by QuintenQVD0** [comment]
Thats sort of the github api that is wrong but yes. I can look in to that.
