### ISSUE TITLE
[Egg Request]: DayZ Dedicated Server (Stable)

### ISSUE THREAD

**Issue by m70b1jr** [pelican-eggs/games-standalone#15]
### Does this expand an already existing service

Yes

### Link to a game or software

https://steamdb.info/app/223350/depots/

### Links for the download

steamcmd?

### Links for the install docs

https://community.bistudio.com/wiki/DayZ:Hosting_a_Linux_Server

Hey! It seems recently within the past month or so (according to the DayZ Discord, and the links above) DayZ Dedicated Server (Stable) can now run on Linux. I was hoping we could get this looked into soon :)

**Comment by QuintenQVD0** [comment]
Wrong repo, you need to be in the steamcmd one, and look their at the open PR, it is already their.
