### ISSUE TITLE
[Bug]: egg-pterodactyl-beam-m-p-servers

### ISSUE THREAD

**Issue by Quentins404** [pelican-eggs/games-standalone#22]
### Panel Version

1.11.7

### Wings Version

1.11.13

### Service

/beamng/beammp/egg-beam-m-p-servers.json

### Modified

No, I did not modify the egg

### Expected Behavior

Do a normal installation with the egg.
The installation completes.
The server starts.

### Actual Behavior

Do a normal installation with the egg.
And the server crashed with exit code 0

![error beammp 1](https://github.com/user-attachments/assets/0cec6289-a4df-4ad3-9791-4a96a011c373)

### Steps To Reproduce

Create a server with the latest egg
Get the error

### Install logs

https://ptero.co/axojuzizaq

**Comment by gOOvER** [comment]
test this pls

https://github.com/pelican-eggs/games-standalone/pull/23
