### ISSUE TITLE
[Bug]: factorio

### ISSUE THREAD

**Issue by andy01745** [pelican-eggs/games-standalone#38]
### Panel Version

1.11.7

### Wings Version

1.11.13

### Service

games-standalone/factorio /factorio/

### Modified

Yes, I modified the egg (will provide details below)

### Expected Behavior

Install and start play

### Actual Behavior

[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ ./bin/x64/factorio --port ${SERVER_PORT} --server-settings data/server-settings.json --start-server ${SAVE_NAME}.zip
./bin/x64/factorio: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./bin/x64/factorio)
./bin/x64/factorio: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_2.30' not found (required by ./bin/x64/factorio)

### Steps To Reproduce

Install and start the server

### Install logs

https://nothing_to_do_with_wings

**Comment by QuintenQVD0** [comment]
What is the Docker image sert to?

**Comment by andy01745** [comment]
quay.io/parkervcp/pterodactyl-images:base_debian

**Comment by andy01745** [comment]
Fixed updated the docker image.
