### ISSUE TITLE
[Egg Request]: KSP - Luna Multiplayer

### ISSUE THREAD

**Issue by Czekoloczek** [pelican-eggs/games-standalone#40]
### Does this expand an already existing service

Yes

### Link to a game or software

https://lunamultiplayer.com/

### Links for the download

https://github.com/LunaMultiplayer/LunaMultiplayer/releases

### Links for the install docs

https://github.com/LunaMultiplayer/LunaMultiplayer/wiki/Create-a-server

**Comment by gOOvER** [comment]
https://github.com/pelican-eggs/games-standalone/tree/main/ksp

As i know, is KPS Luna abdoned

**Comment by QuintenQVD0** [comment]
closed as it already exsist

**Comment by Czekoloczek** [comment]
> https://github.com/pelican-eggs/games-standalone/tree/main/ksp
> 
> As i know, is KSP Luna abdoned

It doesn't seem like it's abandoned, last nightly release was in September
![obraz](https://github.com/user-attachments/assets/7d9ac9ad-b3f8-4596-a4ff-d3743be14203)

**Comment by Czekoloczek** [comment]
> closed as it already exsist 

were?
I could only find "Dark Multiplayer" for ksp

**Comment by QuintenQVD0** [comment]
> > closed as it already exsist
> 
> were? I could only find "Dark Multiplayer" for ksp

I tried to make this in the pases. But the projects is a liite unmaintaind. I will try again but only there layest beta will be supporting aa everyhing is using dotnet 5
